version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: calculator-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_DATABASE: fuel_calculator_localization
      MYSQL_USER: test
      MYSQL_PASSWORD: Test123
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 2s
      retries: 10

  app:
    image: irakump/otp-week2-localization:latest
    container_name: fuel-calculator-app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: test
      DB_PASSWORD: Test123
      DISPLAY: host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  db_data:
