sonar.projectKey=otp-week2-localization
sonar.projectName=otp-week2-localization

sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/CalculatorApp.java,**/CalculatorController.java,**/LocalizationService.java,**/JdbcCalculationRepository.java,**/DatabaseConnection.java

sonar.coverage.exclusions=**/CalculatorApp.java,**/CalculatorController.java,**/LocalizationService.java,**/JdbcCalculationRepository.java,**/DatabaseConnection.java

sonar.host.url=http://localhost:9000

# run with (after Sonar Scanner is turned on from terminal, use StartSonar.bat):
# mvn clean verify sonar:sonar "-Dsonar.projectKey=otp-week2-localization" "-Dsonar.login=$env:SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"
